// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection: Neon's pooled
    // connection string runs through PgBouncer in transaction mode, which
    // breaks the session-level advisory lock `prisma migrate deploy` takes.
    // Falls back to DATABASE_URL for local dev, where there's no pooler.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
